### ISSUE TITLE
Mongoskin: 报错

### ISSUE THREAD

**Issue by yangbo5207** [yangbo5207/everyday#26]
在我如下命令启动`express`应用时，报错
```js
// ~/integration/front-end-road/022.testapp
$ npm start
```

```js
/Users/yangbo/develop/integration/front-end-road/022.testapp/node_modules/mongoskin/lib/utils.js:33
  var skinClassName = 'Skin' + NativeClass.name;
                                          ^

TypeError: Cannot read property 'name' of undefined
    at makeSkinClass (/Users/yangbo/develop/integration/front-end-road/022.testapp/node_modules/mongoskin/lib/utils.js:33:43)
    at Object.<anonymous> (/Users/yangbo/develop/integration/front-end-road/022.testapp/node_modules/mongoskin/lib/grid.js:6:35)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/yangbo/develop/integration/front-end-road/022.testapp/node_modules/mongoskin/lib/db.js:22:16)
    at Module._compile (module.js:425:26)
```

**Comment by yangbo5207** [comment]
一些有帮助的链接
https://github.com/Automattic/monk/issues/91

**Comment by yangbo5207** [comment]
在我安装`monk`组件时，提示如下
```js
└─┬ monk@1.0.1
  ├── UNMET PEER DEPENDENCY mongodb@~1.4
  └── mongoskin@1.4.13

npm WARN EPEERINVALID mongoskin@1.4.13 requires a peer of mongodb@~1.4 but none was installed.
```
因此是依赖错误，发现我安装的`mongodb`组件是2.0.4，因此将该组件删除，重新安装如下
```js
$ npm install mongodb@~1.4 --save
```

安装完成之后，再使用如下指令启动应用，搞定
```js
$ npm start
```
